batch_size = 64
# clip_aug_prob = 0.05
clip_aug_prob = 0.0
clip_aug_mode = 'y'
first_batch = True
wandb_log = False
n_samples_save = 2
ckpt_saving = False
outdir = "~/data/neuro/models/prior/test"
num_epochs = 200